#!/bin/bash

# Atualizar o sistema
apt update

# Instalar Python 3 e pip
apt install -y python3 python3-pip

# Remover o diretório /usr/lib/python3.*/EXTERNALLY-MANAGED
rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED


echo "Instalação do FFmpeg, Python 3 e pip concluída com sucesso."
echo "O diretório /usr/lib/python3.*/EXTERNALLY-MANAGED foi removido."

