#!/bin/bash

# Atualizar o sistema
apt update

# Instalar Python 3 e pip
apt install -y python3 python3-pip

# Remover o diretório /usr/lib/python3.*/EXTERNALLY-MANAGED
rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED


echo "Python 3 e pip concluída com sucesso."
echo "Python 3 and pip completed successfully."
echo "O diretório /usr/lib/python3.*/EXTERNALLY-MANAGED foi removido."
echo "The /usr/lib/python3.*/EXTERNALLY-MANAGED directory has been removed."
